# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'superMovie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SuperPlayer'
  # Pods for superMovie

  target 'superMovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'superMovieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
