# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LearnSwiftApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
  # Pods for LearnSwiftApp

  target 'LearnSwiftAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnSwiftAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
