# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JavaScriptBridgeDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'WebViewJavascriptBridge'
  # Pods for JavaScriptBridgeDemo

  target 'JavaScriptBridgeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JavaScriptBridgeDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
